### ISSUE TITLE
Volcanion Den Glitched Out [ATLAS]

### ISSUE THREAD

**Issue by ProfAwesome100** [NebulaMC-GG/Support#1350]
![image](https://user-images.githubusercontent.com/60492306/172258300-b30c49c9-5067-452d-9beb-6e360a7b5f2b.png)
Volcanion den spawned and crashed on us: ProfAwesome100, miguikpv, BlazeKnight, themaster6869
Here's the logs for the crash

> [01:38:51] [main/INFO]: Mapping halted in C:\Users\USER\AppData\Roaming\ATLauncher\instances\901\journeymap\data\mp\Oblique\minecraft:spawn
[01:38:51] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[01:38:51] [main/INFO]: [CHAT] [Premier] themaster6869: 1 more
[01:38:52] [main/INFO]: Loaded 26 waypoints from C:\Users\USER\AppData\Roaming\ATLauncher\instances\901\journeymap\data\mp\Oblique\waypoints
[01:38:52] [main/INFO]: Mapping started in C:\Users\USER\AppData\Roaming\ATLauncher\instances\901\journeymap\data\mp\Oblique\overworld. Memory: 3808MB total, 1274MB free 
[01:38:55] [main/INFO]: [CHAT] [Premier] Gn_ar_r: \
[01:38:55] [main/INFO]: [CHAT] [GymLeader] Bluespider20: dogi werent u in the desert
[01:38:58] [main/INFO]: [CHAT] [Mod] __Project: i was
[01:39:06] [main/INFO]: [CHAT] 
[01:39:06] [main/INFO]: [CHAT]            ????????????????????? ? ?????????????????????
[01:39:06] [main/INFO]: [CHAT]       Consider purchasing a rank, they include a range of 
[01:39:06] [main/INFO]: [CHAT]                     commands, perks and benefits! 
[01:39:06] [main/INFO]: [CHAT] 
[01:39:08] [main/INFO]: [CHAT] [+] avadeer
[01:39:20] [main/INFO]: [CHAT] >>> Welcome SloppyBox to NebulaMC Atlas! <<<
[01:39:20] [main/INFO]: [CHAT] [+] SloppyBox
[01:39:41] [main/INFO]: [CHAT] [Premier] themaster6869: did someone crash?
[01:39:50] [main/INFO]: [CHAT] [Premier] GrinchsUltimatum: lmaooooo
[01:39:57] [main/INFO]: [CHAT] [Premier] BudderLordK1ng: ummmm
[01:40:00] [main/INFO]: [CHAT] [Premier] BudderLordK1ng: where are all the pokemon
[01:40:39] [main/INFO]: [CHAT] 
[01:40:39] [main/INFO]: [CHAT]            ????????????????????? ? ?????????????????????
[01:40:39] [main/INFO]: [CHAT]            Use the Apex Pixelmon '/modpack' to enhance 
[01:40:39] [main/INFO]: [CHAT]                 gameplay and have custom additions! 
[01:40:39] [main/INFO]: [CHAT] 
[01:40:44] [main/INFO]: [CHAT] [Premier] CyaniteWolf: did anyone catch the volcanion
[01:40:54] [main/INFO]: [CHAT] [-] miguipkv
[01:41:00] [main/INFO]: [CHAT] [Premier] themaster6869: someone crashed
[01:41:04] [main/INFO]: [CHAT] [Premier] themaster6869: so we couldnt do it
[01:41:12] [main/INFO]: [CHAT] [Premier] CyaniteWolf: was it a raid?
[01:41:16] [main/INFO]: [CHAT] [Premier] themaster6869: ya
[01:41:18] [main/INFO]: [CHAT] [Premier] CyaniteWolf: damn
[01:41:22] [main/INFO]: [CHAT] [Premier] nightmaresquid: You should put a ticket in
[01:41:24] [main/INFO]: [CHAT] [Premier] themaster6869: i should have just done it alone i guess
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ClassCastException: sun.java2d.HeadlessGraphicsEnvironment cannot be cast to sun.awt.Win32GraphicsEnvironment
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.awt.windows.WToolkit$3.run(WToolkit.java:834)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventQueue.access$500(EventQueue.java:97)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventQueue$3.run(EventQueue.java:709)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventQueue$3.run(EventQueue.java:703)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.AccessController.doPrivileged(Native Method)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[01:41:26] [AWT-EventQueue-0/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[01:41:32] [main/INFO]: [CHAT] [Premier] Dragon_King5: does anyone have a fossil restorer?
[01:41:32] [main/INFO]: [CHAT] [Premier] xTwilly: you can prob ask about that in support
[01:41:37] [main/INFO]: [CHAT] i[Rune]i MrVoodoo: Whatt I didn't know raids could be legends
[01:41:39] [main/INFO]: [CHAT] [Premier] GrinchsUltimatum: japed out of volcanion

Thanks,
Prof :)

**Comment by Rasgnarok** [comment]
Legendaries should not be spawning in dens, closing.
